name: dav5400
channels:
    - conda-forge
dependencies:
    - python=3.10
    - beautifulsoup4
    - black
    - jupyterlab
    - matplotlib
    - numpy
    - pandas
    - pip
    - pytest
    - requests
    - scikit-learn
    - seaborn
    - selenium
    - sqlalchemy
